# Generated by Django 5.2.7 on 2025-10-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resident_confirmation',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='resident_id_photo',
            field=models.FileField(blank=True, null=True, upload_to='resident_ids/'),
        ),
    ]
