# Generated by Django 5.2.7 on 2025-10-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_resident_confirmation_user_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resident_id_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='resident_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
