# Generated by Django 5.2.7 on 2025-10-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_resident_id_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=20, null=True),
        ),
    ]
