# Generated by Django 5.2.7 on 2025-10-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resident_id_photo',
            field=models.FileField(blank=True, null=True, upload_to='resident_ids/'),
        ),
    ]
