# Generated by Django 5.2.6 on 2025-10-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_resident_id_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nso_document',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resident_id_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
