# Generated by Django 5.2.6 on 2025-10-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetcode'),
        ('accounts', '0008_alter_user_nso_document_alter_user_profile_photo_and_more'),
    ]

    operations = [
    ]
