# Generated by Django 5.2.6 on 2025-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_certificaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('paid', 'Paid'), ('failed', 'Failed Payment Verification')], default='unpaid', max_length=20),
        ),
    ]
