# Generated by Django 5.2.6 on 2025-11-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_certificaterequest_business_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-created_at']},
        ),
    ]
