# Generated by Django 5.2.6 on 2025-11-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_incidentreport_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterequest',
            name='proof_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nso_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resident_id_photo',
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='proof_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nso_document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resident_id_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['user', '-created_at'], name='accounts_ce_user_id_828b62_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['payment_status'], name='accounts_ce_payment_4703a6_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['certificate_type'], name='accounts_ce_certifi_cc5a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['user', '-created_at'], name='accounts_in_user_id_ba6d54_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['status'], name='accounts_in_status_6ca67a_idx'),
        ),
    ]
