# Generated by Django 5.2.6 on 2025-11-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_url_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nso_document_url',
        ),
    ]
