# Generated by Django 5.2.6 on 2025-12-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='claim_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready for Claim'), ('claimed', 'Claimed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
